name: mymoney
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  auto_size_text: ^2.1.0
  sembast: ^2.4.8
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.otf
      - asset: assets/fonts/Montserrat-Light.otf
      - asset: assets/fonts/Montserrat-Bold.otf

  assets:
    - assets/images/
